<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions targetNamespace="http://eHealth.gov.sk/eHtalk" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://eHealth.gov.sk/eHtalk" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://eHealth.gov.sk/eHtalk/Imports">
      <xsd:import schemaLocation="SyncServiceExt_0.xsd" namespace="http://eHealth.gov.sk/eHtalk"/>
      <xsd:import schemaLocation="SyncServiceExt_1.xsd" namespace="http://eHealth.gov.sk/eHtalkMessage"/>
      <xsd:import schemaLocation="SyncServiceExt_2.xsd" namespace="http://eHealth.gov.sk/Common/v1"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="IeHealthSyncService_GetData_InputMessage">
    <wsdl:part name="parameters" element="tns:GetData"/>
  </wsdl:message>
  <wsdl:message name="IeHealthSyncService_GetData_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetDataResponse"/>
  </wsdl:message>
  <wsdl:portType name="IeHealthSyncService">
    <wsdl:operation name="GetData">
      <wsdl:input wsaw:Action="http://eHealth.gov.sk/eHtalk/IeHealthSyncService/Receive" message="tns:IeHealthSyncService_GetData_InputMessage"/>
      <wsdl:output wsaw:Action="http://eHealth.gov.sk/eHtalk/IeHealthSyncService/ReceiveResponse" message="tns:IeHealthSyncService_GetData_OutputMessage"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>